// Типы приходят из @msc/domain: там же лежат zod-схемы, которыми их валидирует сервер.
export type {
  ApiErrorBody,
  Category,
  Contact,
  Home,
  HouseSearchItem,
  JoinInput,
  Liability,
  LiabilityStep,
  Location,
  LocationScope,
  Me,
  Measurement,
  MeasurementPlace,
  NewRequestInput,
  Provenance,
  RequestDetail,
  RequestEvent,
  RequestKind,
  RequestStatus,
  RequestSummary,
  Role,
  Schedule,
  Service,
} from '@msc/domain';
